site_name: Teams app camp
site_url: https://microsoft.github.io/app-camp
repo_url: https://github.com/microsoft/app-camp
repo_name: microsoft/app-camp
edit_uri: ''                    # Disable edit button
extra_css:
    - assets/labStyles.css
nav: 
- Home: 'index.md'
- A Path: 
  - A01 - Start with Azure Active Directory: 'aad/A01-begin-app.md'
  - A02 - Create a Teams app with Azure AD Teams SSO: 'aad/A02-after-teams-sso.md'
  - A03 - Teams styling and themes: 'aad/A03-after-apply-styling.md'
- B Path: 
  - B01 - Start with a non-Azure Active Directory Identity System: 'bespoke/B01-begin-app.md'
  - B02 - Teams App with Bespoke Authentication: 'bespoke/B02-after-teams-login.md'
  - B03 - Enable Azure AD Single Sign-On: 'bespoke/B03-after-teams-sso.md'
  - B04 - Teams styling and themes: 'bespoke/B04-after-apply-styling.md'
- Extended labs:
  - Choose your own adventure!: 'aad/ExtendedLabs.md'
  - Add a configurable tab: 'aad/ConfigurableTab.md'
  - Add a Deep link to a personal Tab: 'aad/Deeplink.md'
  - Add a Dialog: 'aad/Dialog.md'
  - Add a Meeting app: 'aad/MeetingConfigurableTab.md'
  - Add a Message Extension: 'aad/MessagingExtension.md'
  - Selling Your SaaS-based Teams Extension: 'aad/Monetization.md'
  - Extend teams app to Outlook and Microsoft365 app: 'aad/ExtendTeamsApp.md'
- Resources: 
  - More Information: 'Resources.md'
  - Lead your own App Camp: 'in-a-box/index.md'
theme:
  name: 'material'
  palette: 
    primary: 'brown'
    accent: 'deep orange'
  logo: 'assets/code-lab-banner.png'
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs         # Top nav
    - navigation.tabs.sticky  # Make top nav stay vaisible
    - navigation.sections
    - toc.integrate           # Integrate sections into left nav
markdown_extensions:
  - pymdownx.snippets:
      base_path: docs/includes
  - admonition
  - pymdownx.details
  - attr_list


